volumes:
 gif-db:
services:
    app:
        image: node:12-alpine
        command: npm run dev
        working_dir: /usr/local/app
        volumes:
            - ./:/usr/local/app
            - ./mongo-config-sample.json:/run/secrets/mongo-config.json
            - ./mongo-config-sample.json:/sample/location/mongo-config.json
        environment:
            CUSTOM_MESSAGE: This is my custom message!
            MONGO_CONFIG_FILE: /sample/location/mongo-config.json
        ports:
            - 3000:3000
        links:
            - "db:mongo"
    db:
        image: mongo:4.4

        volumes:
            - gif-db:/data/db
            
    dbui:
        image: mongo-express
        ports:
            - "8080:8081"
        environment:
            - ME_CONFIG_MONGODB_SERVER=db