version: "3.8"
volumes:
 gif-db:
services:
    app:
        image: dtoms/gif-collection:latest
        working_dir: /usr/local/app
        networks:
            - default
            - monitoring
            - proxy
        deploy:
            replicas: 3
            # placement:
                # constraints:
                   # - "node.role==worker"
            update_config:
                parallelism: 1
                delay: 10s
                order: start-first
            labels:
              traefik.http.routers.app.rule: Host(`app.localhost`)
              traefik.http.services.app.loadbalancer.server.port: 3000
    mongo:
        image: mongo:4.4

        volumes:
            - gif-db:/data/db
            
    mongo-ui:
        image: mongo-express
        environment:
            - ME_CONFIG_MONGODB_SERVER=db
        deploy:
            labels:
              traefik.http.routers.mongo-ui.rule: Host(`mongo-ui.localhost`)
              traefik.http.services.mongo-ui.loadbalancer.server.port: 8081
        networks:
            - proxy
networks:
    monitoring:
        external: true
    proxy:
        external: true